### ISSUE TITLE
Layers [fr]

### ISSUE THREAD

**Issue by MacMan23** [douglasZwick/blb#35] opened 2024-01-07 10:52 UTC
**Tell us the feature you'd like**
Adding on to #13, there will be multiple layers that you can draw on.
Layers can be created and deleted.
Heroes can be placed on any layer.
Teleporters pairs can be placed on separate layers allowing teleportation to other layers. This would need a camera layer swap transition.
Layers in the background will be shrunk and grayed out a bit to show depth.
Foreground layers should either be invisible, or be larger and brighter to white. 
Layers would parallax with the camera in the proper direction based on if they are in the foreground or background.

**Do you have any additional insight?**
If placement of multiple heroes is allowed then the camera focus can break as only one layer can be in focus at once.

**Comment by douglasZwick** [comment] 2024-01-14 03:03
Currently, I'm nixing the idea of putting heroes or enemies or similar categories of dynamic physics objects into any layer other than the main layer. Without that, this issue becomes basically a duplicate of #13.

**Closed by douglasZwick** 2024-01-14 03:03 UTC
Labels: duplicate, enhancement, wontfix
